[package]
name = "msts-rs"
version = "0.1.0"
authors = ["ashcon"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compress="0.2.1"
byteorder="1.3.4"
image="0.23.13"
